title: Pablo Tapia Varela
description: Ingeniero Comercial ( :zipper_mouth_face: ) de la Universidad Adolfo Ibañez. Msc in Finance Universidad Adolfo Ibañez.
Intereses en Text Mining, Stock Market, Football Analysis.
theme: jekyll-theme-minimal
markdown: kramdown 
url: https://github.com/pablotapiav

:zipper_mouth_face:

### Me pueden encontrar en:

**Linkedin:** [Perfil](https://www.linkedin.com/in/pablo-tapia-varela-9b094523/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BVIUFvgF2SOW33lG6nqwZIg%3D%3D&licu=urn%3Ali%3Acontrol%3Ad_flagship3_feed-nav.settings_view_profile)

**Medium:** [@pablotv](https://medium.com/@pablotv)
