title: Pablo Tapia Varela
description: Ingeniero Comercial de la Universidad Adolfo Ibanez. Msc in Finance Universidad Adolfo Ibanez.
theme: jekyll-theme-minimal
markdown: kramdown 
url: https://github.com/pablotapiav
