title: Pablo Tapia Varela
description: R Analysis, Risk financial, Football Analysis, SQL, Power Bi, Shiny Apps.
theme: jekyll-theme-minimal
markdown: kramdown 
url: https://github.com/pablotapiav

plugins:
  - jemoji
